[package]
name = "oxcr_server"
version = "0.1.0"
edition = "2021"

[dependencies]
oxcr_net.workspace = true
tokio.workspace = true
apecs.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"
