[package]
name = "oxcr_server"
version = "0.1.0"
edition = "2021"

[dependencies]
oxcr_protocol.workspace = true
tokio.workspace = true
bevy.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
