[package]
name = "oxcr_server"
version = "0.1.0"
edition = "2021"

[dependencies]
oxcr_protocol.workspace = true
oxcr_cli.workspace = true
tokio.workspace = true
tokio-util.workspace = true
bevy.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
futures-util = "0.3.28"
